language: node_js
node_js:
  - "node"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database trailblazers_reviews;' -U postgres
  - npm run db:init
  - npm run db:setup

jobs:
  include:
    - stage: Produce Coverage
    - script: npm run lint
    - script: jest --detectOpenHandles --verbose
    - script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
