language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: Lint
    - script: npm run lint
  include: 
    - stage: Test
    - script: npm test
  include:
    - stage: Produce Coverage
    - script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
